"""add appearance fields to agent

Revision ID: 01a0ba05702e
Revises: b48e6f27c0cc
Create Date: 2025-08-03 15:30:54.443561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a0ba05702e'
down_revision: Union[str, Sequence[str], None] = 'b48e6f27c0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('hair_style', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('eye_color', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('ethnicity', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('body_type', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('clothing', sa.String(), nullable=True))
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_column('agents', 'clothing')
    op.drop_column('agents', 'body_type')
    op.drop_column('agents', 'height')
    op.drop_column('agents', 'age')
    op.drop_column('agents', 'ethnicity')
    op.drop_column('agents', 'eye_color')
    op.drop_column('agents', 'hair_style')
    # ### end Alembic commands ###
