"""remove height from agents

Revision ID: 08bf271010ac
Revises: 71c0a7c2e9be
Create Date: 2025-08-13 09:25:05.885665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bf271010ac'
down_revision: Union[str, Sequence[str], None] = '71c0a7c2e9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'height')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
