"""Add relationship_status and hair_color to agents

Revision ID: 88ed787c65f2
Revises: 6c8564fad998
Create Date: 2025-08-07 16:00:41.056890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ed787c65f2'
down_revision: Union[str, Sequence[str], None] = '6c8564fad998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('relationship_status', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('hair_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'hair_color')
    op.drop_column('agents', 'relationship_status')
    # ### end Alembic commands ###
