"""add first_person to agents

Revision ID: 8986e44a7456
Revises: 88ed787c65f2
Create Date: 2025-08-07 16:20:58.797531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8986e44a7456'
down_revision: Union[str, Sequence[str], None] = '88ed787c65f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('first_person', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('first_person_other', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'first_person_other')
    op.drop_column('agents', 'first_person')
    # ### end Alembic commands ###
