"""add second_person to agents

Revision ID: 89e8383c8715
Revises: 8986e44a7456
Create Date: 2025-08-07 16:48:08.627726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e8383c8715'
down_revision: Union[str, Sequence[str], None] = '8986e44a7456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('second_person', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'second_person')
    # ### end Alembic commands ###
