"""Add image_url to messages

Revision ID: 9a5caa1f1ac9
Revises: 56a455303d89
Create Date: 2025-07-30 16:47:59.373665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5caa1f1ac9'
down_revision: Union[str, Sequence[str], None] = '56a455303d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'image_url')
    # ### end Alembic commands ###
