"""Add agent profile properties and tag tables

Revision ID: b48e6f27c0cc
Revises: 9a5caa1f1ac9
Create Date: 2025-07-30 19:52:28.004717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48e6f27c0cc'
down_revision: Union[str, Sequence[str], None] = '9a5caa1f1ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_personalities_id'), 'personalities', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('tones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tones_id'), 'tones', ['id'], unique=False)
    op.create_table('agent_personalities',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('personality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'personality_id')
    )
    op.create_table('agent_roles',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'role_id')
    )
    op.create_table('agent_tones',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('tone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tone_id'], ['tones.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'tone_id')
    )
    op.add_column('agents', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('background', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    
    # Insert dummy data
    # Personalities
    op.execute("""
        INSERT INTO personalities (name) VALUES 
        ('友好的'),
        ('冷静'),
        ('情熱的'),
        ('論理的'),
        ('ユーモラス'),
        ('真面目'),
        ('優しい'),
        ('厳格')
    """)
    
    # Roles
    op.execute("""
        INSERT INTO roles (name) VALUES 
        ('教師'),
        ('コンサルタント'),
        ('エンジニア'),
        ('医師'),
        ('カウンセラー'),
        ('マネージャー'),
        ('研究者'),
        ('アシスタント')
    """)
    
    # Tones
    op.execute("""
        INSERT INTO tones (name) VALUES 
        ('丁寧'),
        ('カジュアル'),
        ('フォーマル'),
        ('親しみやすい'),
        ('専門的'),
        ('シンプル'),
        ('詳細'),
        ('励まし')
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'background')
    op.drop_column('agents', 'gender')
    op.drop_table('agent_tones')
    op.drop_table('agent_roles')
    op.drop_table('agent_personalities')
    op.drop_index(op.f('ix_tones_id'), table_name='tones')
    op.drop_table('tones')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_personalities_id'), table_name='personalities')
    op.drop_table('personalities')
    # ### end Alembic commands ###
