"""Add image_seed to agents table

Revision ID: fb49bbd54588
Revises: 6e337a675946
Create Date: 2025-08-08 12:03:52.587635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb49bbd54588'
down_revision: Union[str, Sequence[str], None] = '6e337a675946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_images', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_agent_images_agent_id'), table_name='agent_images')
    op.add_column('agents', sa.Column('image_seed', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'image_seed')
    op.create_index(op.f('ix_agent_images_agent_id'), 'agent_images', ['agent_id'], unique=False)
    op.alter_column('agent_images', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
